@startuml

abstract Class Mobile {
    + String : get_nom()
    + void : set_nom(String)
    + double : get_x()
    + double : get_y()
    + void : set_x(double)
    + void : set_y(double)
    + void : set_position(double, double)
    + {abstract} void : dessiner(double xx=0, double yy=0 + String porteur="")
    + {abstract} void : deplacer(double)
    + void : update()
    + bool : controle()

}


@enduml
