@startuml

skinparam activityArrowFontSize 24

' Ajout des classes
!include AdaptativeGVporteur.puml
!include AdaptativeGVsimple.puml
!include AfficheContenu.puml
!include Arbre.puml
!include ArbreType.puml
!include Commande.puml
!include Fruit.puml
!include GestionnaireArbreType.puml
!include Grandir.puml
!include GroundVehicule.puml
!include Mobile.puml
!include MobileProxy.puml
!include MobileInterface.puml
!include MobilePorteur.puml
!include MobileSimple.puml
!include Monde.puml
!include Neige.puml
!include Saison.puml
!include Vegetal.puml
!include VegetalProxy.puml
!include VegetalInterface.puml
!include VegetalDecore.puml

' Héritage
MobilePorteur <|-- AdaptativeGVporteur
MobileSimple <|-- AdaptativeGVsimple

VegetalInterface <|-- VegetalProxy
VegetalInterface <|-- Vegetal

MobileInterface <|-- MobileProxy
MobileInterface <|-- Mobile

Vegetal <|-- Arbre
Vegetal <|-- VegetalDecore

VegetalDecore <|-- Fruit
VegetalDecore <|-- Neige

Mobile <|-- MobilePorteur
Mobile <|-- MobileSimple

Commande <|-- AfficheContenu
Commande <|-- Grandir
Commande <|-- Saison

' Aggrégation
Arbre o--> "1" ArbreType : at
MobilePorteur o--> "*" Mobile : mobiles_portes

Monde o--> "1" GestionnaireArbreType : gat
Monde o--> "*" Commande : cmd
Monde o-> "*" MobileInterface : MobilesInterface
Monde o--> "*" Mobile : MesMobiles
Monde o--> "*" VegetalInterface : VegetauxInterface
Monde o--> "*" Vegetal : MesVegetaux


Saison o--> "1" GestionnaireArbreType : cible
VegetalDecore o--> "1" Vegetal : v
GestionnaireArbreType o--> "*" ArbreType : map (key = String)

VegetalProxy o-> " 1" Vegetal : vegetal
Mobile " 1" <-o MobileProxy : mobile

' Composition
AdaptativeGVporteur *--> "1" GroundVehicule
AdaptativeGVsimple *--> "1" GroundVehicule


hide GroundVehicule members
hide AdaptativeGVporteur members
hide AdaptativeGVsimple members
hide GestionnaireArbreType members
hide ArbreType members
hide AfficheContenu members
hide Commande members
hide Grandir members
hide Saison members
hide MobilePorteur members
hide MobileSimple members
hide Fruit members
hide Neige members
hide VegetalDecore members
hide Arbre members



@enduml
