@startuml

skinparam activityArrowFontSize 14

' Héritage
MobileInterface <|-- Mobile
MobileInterface <|-- MobileProxy

Client .> MobileInterface : Interagit avec
MobileProxy o-> "      1" Mobile : mobile

hide member

@enduml
